### ISSUE TITLE
CSS color palette

### ISSUE THREAD

**Issue by MinervaLong** [chingu-voyages/v11-toucans-team-13#7]
Pick the web colors with Colorcilla (or another) browser extension

**Comment by dan9d9** [comment]
These are the colors used on the Chipotle site. I think these are all we will need.

white(#fff) - for background 
#451400	- primary brownish color
#ad2118 - red color (in images and button::hover.
#88120a - darker red in "join now"
#b68207 - dropdown text color
#786259 - light brown for "Find a Chipotle" at bottom (not sure that we'll need this one)
#1b0800 - dark brown for footer
