### ISSUE TITLE
Choose fonts

### ISSUE THREAD

**Issue by MinervaLong** [chingu-voyages/v11-toucans-team-13#8]
Decide if we want the same fonts or another

**Comment by dan9d9** [comment]
I think we just use the same. Here are the font-families used on the site:

The nav uses: "Trade Gothic LT", "Helvetica Neue", Arial, sans-serif;	
Everything else is: "Nunito", "Helvetica Neue" ,Arial, sans-serif;

Helvetica Neue is a system font of Mac, but not available on Windows/Linux. A google font alternative is "IBM Plex Sans"
